NO_PIECE = 0
PAWN = 1
ROOK = 2
KNIGHT = 3
BISHOP = 4
QUEEN = 5
KING = 6

NO_PIECE_REPR = '.'
PAWN_REPR = 'p'
ROOK_REPR = 'r'
KNIGHT_REPR = 'n'
BISHOP_REPR = 'b'
QUEEN_REPR = 'q'
KING_REPR = 'k'

NO_COLOR = 0
WHITE = 1
BLACK = 2

PIECE_ID_TO_TEXT = {
  NO_PIECE: NO_PIECE_REPR,
  PAWN: PAWN_REPR,
  ROOK: ROOK_REPR,
  KNIGHT: KNIGHT_REPR,
  BISHOP: BISHOP_REPR,
  QUEEN: QUEEN_REPR,
  KING: KING_REPR
}

PIECE_TEXT_TO_ID = {
  NO_PIECE_REPR: NO_PIECE,
  PAWN_REPR: PAWN,
  ROOK_REPR: ROOK,
  KNIGHT_REPR: KNIGHT,
  BISHOP_REPR: BISHOP,
  QUEEN_REPR: QUEEN,
  KING_REPR: KING
}
